// /login
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

// /portfolio
export const LOADED_PORTFOLIO_DATA = "LOADED_PORTFOLIO_DATA";
export const START_LOAD_PORTFOLIO_DATA = "START_LOAD_PORTFOLIO_DATA";
export const START_LOAD_PORTFOLIO_STOCK_PRICE = "START_LOAD_PORTFOLIO_STOCK_PRICE";
export const LOADED_PORTFOLIO_STOCK_PRICE = "LOADED_PORTFOLIO_STOCK_PRICE";

// /portfolio, trade history
export const LOADED_TRADE_HISTORY = "LOADED_TRADE_HISTORY";
export const START_LOAD_TRADE_HISTORY = "START_LOAD_TRADE_HISTORY";

// /stock 
export const LOAD_STOCK_DATA = "LOAD_STOCK_DATA";
export const LOAD_STOCK_CHART = "LOAD_STOCK_CHART";
export const LOAD_STOCK_QUOTE = "LOAD_STOCK_QUOTE";
export const LOAD_KEY_STATS = "LOAD_KEY_STATS";
export const LOAD_STOCK_PROFILE = "LOAD_STOCK_PROFILE";
export const START_LOAD_STOCK_DATA = "START_LOAD_STOCK_DATA";



// /stock, submit trade

export const SELECT_SIDE = "SELECT_SIDE";
export const SUBMIT_TRADE = "SUBMIT_TRADE";
export const SUBMIT_INVALID_TRADE = "SUBMIT_INVALID_TRADE";
export const CLOSE_POSITION = "CLOSE_POSITION";

export const MODAL_CONFIRM_TRADE = "MODAL_CONFIRM_TRADE";
export const CLOSE_MODAL = "CLOSE_MODAL";



//Search

export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SYMBOL_NOT_FOUND = "SYMBOL_NOT_FOUND";
