export const LOAD_STOCK_DATA = "LOAD_STOCK_DATA";
export const START_LOAD_STOCK_DATA = "START_LOAD_STOCK_DATA";


export const LOAD_PORTFOLIO_DATA = "LOAD_PORTFOLIO_DATA";
export const START_LOAD_PORTFOLIO_DATA = "START_LOAD_PORTFOLIO_DATA";
