// /login
export const LOGIN = "LOGIN";



// /portfolio
export const LOAD_PORTFOLIO_DATA = "LOAD_PORTFOLIO_DATA";
export const START_LOAD_PORTFOLIO_DATA = "START_LOAD_PORTFOLIO_DATA";


// /stock 
export const LOAD_STOCK_DATA = "LOAD_STOCK_DATA";
export const LOAD_KEY_STATS = "LOAD_KEY_STATS";
export const LOAD_STOCK_PROFILE = "LOAD_STOCK_PROFILE";
export const START_LOAD_STOCK_DATA = "START_LOAD_STOCK_DATA";

export const SELECT_SIDE = "SELECT_SIDE";
export const SUBMIT_TRADE = "SUBMIT_TRADE";
export const SUBMIT_INVALID_TRADE = "SUBMIT_INVALID_TRADE";
export const CLOSE_POSITION = "CLOSE_POSITION";

export const MODAL_CONFIRM_TRADE = "MODAL_CONFIRM_TRADE";
export const CLOSE_MODAL = "CLOSE_MODAL";
